language: python

python:
  - "3.8"

jobs:
  include:
    - stage: "build lab2"
      name: "lab2"
      python: 3.8
      install:
        - cd ./lab2/
        - pipenv install
      script: pipenv run pytest tests/tests.py || true
    - stage: "build lab3"
      name: "run server and tests"
      python: 3.8
      install:
        - cd ./lab3/
        - pipenv install
        - pipenv install requests
        - pipenv install django
      script: bash ./script/travis-build.sh
    - stage: "build lab4"
      name: "build docker"
      services:
        - docker
      install:
        - cd ./lab4/
      script:
        - docker build -t alexolink/study:travis .
        - docker images
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push alexolink/study:travis
    - stage: "build lab5"
      name: "lab5"
      services:
        - docker
      install:
        - cd ./lab5/
        - make app
        - make tests
      script:
        - make run
        - make test-app
branches:
  only:
    - master
